name: deploy to test instance
on:
  push:
    branches: [ cicd ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/ushauri_dashboard/      
          cd /apps/github-workflows/mhealth-apps/ushauri_dashboard/
          git pull origin main
          git status
          cp /apps/configs/ushauri-dashboard/.env /apps/github-workflows/mhealth-apps/ushauri_dashboard/
          composer install --ignore-platform-reqs
          php artisan serve
